"""Visible tests for mathlib (the ones the agent can see).

The buggy implementation fails test_median_even. After your fix all must pass.
Do NOT edit this file.
"""
import math

from src.mathlib import median, clamp, quantile


def test_median_odd():
    assert median([3, 1, 2]) == 2
    assert median([1]) == 1


def test_median_even():
    # median([4, 1, 3, 2]) == 2.5 — currently fails on the buggy build
    assert math.isclose(median([4, 1, 3, 2]), 2.5, abs_tol=1e-9)


def test_median_empty():
    assert median([]) is None


def test_clamp():
    assert clamp(5, 0, 10) == 5
    assert clamp(-3, 0, 10) == 0
    assert clamp(42, 0, 10) == 10


def test_quantile():
    assert math.isclose(quantile([1, 2, 3, 4], 0.5), 2.5, abs_tol=1e-9)